### PR TITLE
more features tested in cargo doc ci step

### PR DESCRIPTION
**Pull request by Vrixyz**
- \+ fix a deprecation warning (https://github.com/rust-lang/rust/issues/120456)

### CODE REVIEW

**Review by waywardmonkeys — COMMENTED** [review]
Seems like there are 3 changes here, so maybe 3 commits are better.

**Comment by waywardmonkeys** [comment]
FWIW, I had a branch that I hadn't submitted yet and it was:

```
commit b9190be36915b2a7d042215fdf10ce9364b4b6fb (ci-check-features-cargo-doc)
Author: Bruce Mitchener <bruce.mitchener@gmail.com>
Date:   Thu Jul 18 08:04:49 2024 +0700

    ci: Enable same features as docs.rs in cargo doc

diff --git a/.github/workflows/rapier-ci-build.yml b/.github/workflows/rapier-ci-build.yml
index 984bb86..3962323 100644
--- a/.github/workflows/rapier-ci-build.yml
+++ b/.github/workflows/rapier-ci-build.yml
@@ -23,7 +23,7 @@ jobs:
     steps:
       - uses: actions/checkout@v4
       - name: Cargo doc
-        run: cargo doc -p rapier3d -p rapier2d -p rapier3d-stl -p rapier3d-urdf
+        run: cargo doc --features parallel,simd-stable,serde-serialize,debug-render -p rapier3d -p rapier2d -p rapier3d-stl -p rapier3d-urdf
   build-native:
     runs-on: ubuntu-latest
     env:
```

Which corresponded to these sorts of configurations:

```
crates/rapier3d/Cargo.toml:[package.metadata.docs.rs]
crates/rapier3d/Cargo.toml-features = ["parallel", "simd-stable", "serde-serialize", "debug-render"]
```

**Comment by Vrixyz** [comment]
> Seems like there are 3 changes here, so maybe 3 commits are better.

You're definitely right ; we usually squash commits though so in the end it wouldn't matter much, one could argue making different PR for all that would be cleaner, I somewhat agree... but as we have limited bandwidth I believe making more holistic PR are more comprehensive and help communication.

But again, theoretically I agree, and your recent very focused PR are top notch, and much more likely to be merged in a reasonable amount, for someone without merging rights. I'm definitely taking advantage of my "membership" 😅.

**Comment by Vrixyz** [comment]
closed in favor of https://github.com/dimforge/rapier/pull/697

**Pull request closed without merging**
