### PR TITLE
Use workspace lints to control unexpected_cfgs.

### PR DESCRIPTION
**Pull request by waywardmonkeys**
By using `workspace.lints`, we can configure lints once for everything (and then inherit it into the various crates).

The lint configuration for `unexpected_cfgs` works in 1.80+ and warns otherwise.

### CODE REVIEW

**Comment by waywardmonkeys** [comment]
I've marked this as a draft as there are unexpected cfgs still that need to be resolved:

* `log` in src_testbed
* `other-backends` isn't configured for `rapier_testbed3d-f64` while it is for the other 3 configurations.

This will generate a warning from `cargo` in Rust 1.79 and earlier (1.80 is due for release soon) and there are already 2 warnings from `cargo` that are more verbose than this one.

I think this replaces #638 from @urgau

To answer one of the concerns from @sebcrozet , advantages of this PR is that we get the benefit of the `unexpected_cfgs` lint again and we can start to use `workspace.lints` to centralize some other lint configurations in the future.

**Comment by waywardmonkeys** [comment]
Now that #684 has landed, I've dealt with the `other-backends` question in here and this should be ready now.

I've confirmed that it builds without warnings on beta builds (warnings from `unexpected_cfgs`).

**Review by Vrixyz — APPROVED** [review]

**Comment by Vrixyz** [comment]
Thanks!

**Comment by waywardmonkeys** [comment]
You're welcome!

**Pull request merged**
